name: update
on:
  push:
    branches:
      - main
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Python script
        run: python3 .github/workflows/update_readme.py
