name: Update README

on:
    push:
    branches:
    - main

jobs:
    update-readme:
    runs-on: ubuntu-latest

    steps:
        - name: Check out code
        uses: actions/checkout@v4 
        run: git checkout 

        - name: Update README
        run: .github\update_readme.py

        - name: Commit changes
        run: |
            git config --global user.name "graciari2000"
            git config --global user.email "youremail@example.com"
            git add README.md
            git commit -m "Update README.md"
            git push