name: update
on:
  push:
    branches:
      - main
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Python script
        run: python3 .github/workflows/update_readme.py

  job-2:
    runs-on: ubuntu-latest
    needs: [job-1]
    name: Commit changes
    steps:
      - name: Configure Git
        run: |
          git config --global user.name "${{ secrets.USER }}"
          git config --global user.email "${{ secrets.EMAIL }}"
          git add README.md
          git commit -m "Update README.md"
          git push
