name: update
on: [push]
branches: 
    - main
jobs:
    job-1:
        checkout:
        steps:
            - name: Checkout code 
            uses: actions/checkout@v2 
                    
    job-2:
        needs: [job-1]
        name: Update README
        steps:
            run: / python3 update_readme.py
                    
    job-3:
        needs: [job-1, job-2]
        name: Commit changes
        steps:
            run: 
                git config --global user.name "${{ secrets.GITHUB_USER }}" 
                git config --global user.email "${{ secrets.GITHUB_EMAIL }}"
                git add README.md
                git commit -m "Update README.md"
                git push